### ISSUE TITLE
What is the main reason behind using frequency bin images rather than raw waveforms ?

### ISSUE THREAD

**Issue by shamanez** [swasun/VQ-VAE-Speech#1]
Seems like it is mainly because of training time of wavenet decoder?

**Comment by swasun** [comment]
@shamanez Actually the main reason is because in [Chorowski et al., 2019] they show that using MFCC or log-mel spectrogram representations instead of raw waveform reach better phoneme recognition accuracy (from the table page 9: https://arxiv.org/pdf/1901.08810.pdf).
